card/urls.py
from django.urls import path
from . import views

app_name = "card"

urlpatterns = [

    path("<str:app_user>/", views.MyCardView, name="card"),
    
    path("card/", views.CardView, name="card"),

]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.IndexView, name="index"),
    path("<str:app_user>/", views.URLProfileView, name="profile"),
]

order/urls.py
from django.urls import path
from . import views

app_name = "order"

urlpatterns = [

    path("order/", views.ShopCartView, name="shopcart"),
    path("shipping/", views.ShippingView, name="shipping"),
    path("complete/<int:id>/", views.CompleteView, name="complete"),
    path("update-profile/<int:order_id>/", views.UpdateAppuserView, name="update_appuser"),

    path("dashboard/<int:id>/", views.DashboardView, name="dashboard"),
    #path("<str:app_user>/", views.URLProfileView, name="profile"),
    path("confirm/", views.ConfirmView, name="confirm"),

]

thispass/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path 


urlpatterns = [
    path("", include("main.urls")),
    path('admin/', admin.site.urls),
    path("app/", include("app_user.urls")),
    path("card", include("card.urls")),
    path("order/", include("order.urls")),
    path("payment/", include("payment.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.utils import timezone

from django.contrib.auth.models import User
from django.forms import ModelForm, TextInput
from card.models import Card
from app_user.models import AppUser
# Create your models here.

from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm, TextInput


# Create your models here.
class ShopCart(models.Model):
	app_user = models.ForeignKey(AppUser, on_delete=models.SET_NULL, null=True)
	card = models.ForeignKey(Card, on_delete=models.SET_NULL, null=True)
	quantity = models.IntegerField(default=1)



	def __str__(self):
		return self.card.name

	@property
	def price(self):
		return (self.card.price)

	@property
	def amount(self):
		return (self.quantity * self.card.price)




class Order(models.Model):
	STATUS = (
			('New', 'New'),
			('Accepted', 'Accepted'),
			('Preapparing', 'Preapparing'),
			('OnShipping', 'OnShipping'),
			('Completed', 'Completed'),
			('Cancelled', 'Cancelled'),
		)
	app_user = models.ForeignKey(AppUser, on_delete=models.SET_NULL, null=True)
	code = models.CharField(max_length=5, editable=False)
	first_name = models.CharField(max_length=125)
	last_name = models.CharField(max_length=125)
	email = models.CharField(max_length=125)
	phone = models.CharField(blank=True, max_length=125)
	address = models.CharField(blank=True, max_length=150)
	city = models.CharField(blank=True, max_length=125)
	state = models.CharField(blank=True, max_length=125)
	postal_code = models.CharField(blank=True, max_length=125)
	country = models.CharField(blank=True, max_length=125)
	total=models.FloatField()
	status = models.CharField(max_length=15, choices=STATUS, default='New')
	adminnote = models.CharField(blank=True ,max_length=125)
	create_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

    
	

class OrderForm(ModelForm):
	class Meta:
		model = Order
		fields = ['first_name', 'last_name', 'email', 'address', 'phone', 'city', 'state', 'postal_code', 'country']


	def __str__(self):
		return self.user.first_name

	def __str__(self):
		return self.card_first_name

class OrderProduct(models.Model):
	STATUS = (
		('New', 'New'),
		('Accepted', 'Accepted'),
		('Cancelled', 'Cancelled'),
		)
	order = models.ForeignKey(Order, on_delete=models.CASCADE)
	app_user = models.ForeignKey(AppUser, on_delete=models.CASCADE)
	card = models.ForeignKey(Card, on_delete=models.CASCADE)
	quantity = models.IntegerField()
	price = models.FloatField()
	status = models.CharField(max_length=15, choices=STATUS, default='New')
	create_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.card.name


class CardInfo(models.Model):
	
    app_user = models.ForeignKey(AppUser, on_delete=models.SET_NULL, null=True)
    card_code = models.CharField(default="",max_length=2000)
    card_first_name = models.CharField(default="",max_length=2000)
    card_last_name = models.CharField(default="",max_length=2000)
    card_phone_no = models.CharField(default="",max_length=100)
    card_email = models.CharField(default="",max_length=2000)
    card_profile_photo = models.FileField(upload_to='account_files/profile_photos/', blank=True, default="default_files/default_face.jpg")
    card_website = models.CharField(default="",max_length=1000)
    card_job_title = models.CharField(default="",max_length=1000)
    card_company = models.CharField(default="",max_length=30, null=True)

    #card address info
    card_address = models.CharField(default="",max_length=30, null=True)
    card_city = models.CharField(default="",max_length=30, null=True)
    card_state = models.CharField(default="",max_length=30, null=True)
    card_zip_code = models.CharField(default="",max_length=30, null=True)
    card_country = models.CharField(default="",max_length=30, null=True)

    #card social links
    facebook_link = models.CharField(default="",max_length=30, null=True)
    twitter_link = models.CharField(default="",max_length=30, null=True)
    instagram_link = models.CharField(default="",max_length=30, null=True)
    linkedin_link = models.CharField(default="",max_length=30, null=True)

    def __str__(self):
    	return self.card_code




	

order/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate

from django.utils.crypto import get_random_string

from datetime import datetime
import datetime as dt
import requests

from card.models import *
from .models import *
#from resume.models import Resume


def ShopCartView(request):
	app_user = AppUser.objects.get(user__pk=request.user.id)
	card = Card.objects.get()
	if request.method == "POST":
		quantity = request.POST.get("quantity")

		cart = ShopCart.objects.create(app_user=app_user, card=card, quantity=quantity)
		cart.save()

		messages.warning(request, "Welldone! Profile Data Updated")
		return HttpResponseRedirect(reverse("order:shipping"))


	else:
		shopcart = Card.objects.all()

		context = {"shopcart":shopcart, "app_user":app_user, "card":card}
		return render(request, "order/cart.html", context )


def ShippingView(request):
	app_user = AppUser.objects.get(user__pk=request.user.id)
	cards = ShopCart.objects.filter(app_user=app_user)
	total=0
	for rs in cards:
		total += rs.card.price * rs.quantity + rs.card.shipping_charge
	if request.method == "POST":
		form = OrderForm(request.POST)
		if form.is_valid():
			data = Order()
			data.first_name = form.cleaned_data['first_name']
			data.last_name = form.cleaned_data['last_name']
			data.email = form.cleaned_data['email']
			data.address = form.cleaned_data['address']
			data.city = form.cleaned_data['city']
			data.state = form.cleaned_data['state']
			data.phone = form.cleaned_data['phone']
			data.country = form.cleaned_data['country']
			data.postal_code = form.cleaned_data['postal_code']
			data.user_id = app_user.id
			data.total = total
			data.ip = request.META.get('REMOTE_ADDR')
			ordercode = get_random_string(5).upper()
			data.code = ordercode
			data.app_user = app_user
			data.save()

			cards = ShopCart.objects.filter(app_user=app_user.id)
			for rs in cards:
				detail = OrderProduct()
				detail.order_id = data.id
				detail.card_id = rs.card_id
				detail.app_user = app_user
				detail.quantity = rs.quantity
				detail.price = rs.card.price
				detail.save()

				card = Card.objects.get(id=rs.card_id)
				card.save()	

			ShopCart.objects.filter(app_user=app_user.id).delete()
			request.session['cart_items']=0

			return HttpResponseRedirect(reverse("payment:make_payment", args=[data.id,]))

			
			#return render(request, 'order/order_complete.html', {'ordercode':ordercode})
		else:
			messages.warning(request, form.errors)
			return HttpResponseRedirect("/order/shipping")	

	else:

		shipping = 0
		for rs in cards:
			shipping = rs.card.shipping_charge

		price = 0
		for rs in cards:
			price = rs.card.price 

		subtotal=0
		for rs in cards:
			subtotal += rs.card.price * rs.quantity


		added=0
		for rs in cards:
			added +=  rs.quantity + shipping

		form = OrderForm()
		context = {
			"app_user":app_user, 
			"cards":cards, 
			"price":price, 
			"subtotal":subtotal,
			'added':added, 
			'total':total, 
			'shipping':shipping,
			'form':'form',}
		return render(request, "order/shipping.html", context )

def CompleteView(request, id):
	app_user = AppUser.objects.get(user__pk=request.user.id)
	if request.method == "POST":
		pass
	else:
		card = CardInfo.objects.get(id=id)
		context = {"app_user":app_user, "card":card}
		return render(request, "order/order_complete.html", context )

def UpdateAppuserView(request, order_id):
	order = Order.objects.get(id=order_id)
	app_user = AppUser.objects.get(user__pk=request.user.id)
	if request.method == "POST":
		#card primary info
		try:
			card_profile_photo = request.FILES["card_profile_photo"]
		except:
			card_profile_photo = card.card_profile_photo
		app_user = AppUser.objects.get(user__pk=request.user.id)
		card_first_name = request.POST.get("card_first_name")
		card_last_name = request.POST.get("card_last_name")
		card_code = request.POST.get("card_code")
		card_email = request.POST.get("card_email")
		card_company = request.POST.get("card_company")
		card_phone_no = request.POST.get("card_phone_no")
		card_website = request.POST.get("card_website")
		card_job_title = request.POST.get("card_job_title")

		#card address info
		card_address = request.POST.get("card_address")
		card_city = request.POST.get("card_city")
		card_state = request.POST.get("card_state")
		card_zip_code = request.POST.get("card_zip_code")
		card_country = request.POST.get("card_country")

		#card socil info
		facebook_link = request.POST.get("facebook_link")
		twitter_link = request.POST.get("twitter_link")
		instagram_link = request.POST.get("instagram_link")
		linkedin_link = request.POST.get("linkedin_link")

		app_user = CardInfo.objects.create(
			card_profile_photo=card_profile_photo,
			app_user=app_user, 
			card_code=card_code,
			card_first_name=card_first_name, 
			card_last_name=card_last_name, 
			card_email=card_email, 
			card_company=card_company, 
			card_phone_no=card_phone_no,
			card_website=card_website,
			card_job_title=card_job_title,
			card_address=card_address,
			card_country=card_country,
			card_city=card_city,
			card_state=card_state,
			card_zip_code=card_zip_code,
			facebook_link=facebook_link,
			twitter_link=twitter_link,
			instagram_link=instagram_link,
			linkedin_link=linkedin_link,
		)
		app_user.save()
	
			
		
		return HttpResponseRedirect(reverse("order:confirm"))
			
	else:
		app_user = AppUser.objects.get(user__pk=request.user.id)

		context = {"app_user":app_user, "order":order}
		return render(request, "order/update_profile.html", context )

def ConfirmView(request):
	app_user = AppUser.objects.get(user__pk=request.user.id)
	card_info = CardInfo.objects.all().order_by('-id')[:1]
	if request.method == "POST":
		pass


	else:


		context = {"app_user": app_user, "card_info":card_info}
		return render(request, "order/confirm_details.html", context )


def DashboardView(request, id):
	order = Order.objects.all()
	card = CardInfo.objects.get(id=id)
	app_user = AppUser.objects.get(user__pk=request.user.id)
	if request.method == "POST":
		app_user = AppUser.objects.get(user__pk=request.user.id)
		card_first_name = request.POST.get("card_first_name")
		card_last_name = request.POST.get("card_last_name")
		card_email = request.POST.get("card_email")
		card_company = request.POST.get("card_company")
		card_phone_no = request.POST.get("card_phone_no")
		card_website = request.POST.get("card_website")
		card_job_title = request.POST.get("card_job_title")

		card_address = request.POST.get("card_address")
		card_city = request.POST.get("card_city")
		card_state = request.POST.get("card_state")
		card_zip_code = request.POST.get("card_zip_code")
		card_country = request.POST.get("card_country")

		facebook_link = request.POST.get("facebook_link")
		twitter_link = request.POST.get("twitter_link")
		instagram_link = request.POST.get("instagram_link")
		linkedin_link = request.POST.get("linkedin_link")


		card.card_first_name = card_first_name
		card.card_last_name = card_last_name
		
		card.card_email = card_email
		card.card_company = card_company
		card.card_phone_no = card_phone_no
		card.card_website = card_website
		card.card_job_title = card_job_title

		card.card_address = card_address
		card.card_city = card_city
		card.card_state = card_state
		card.card_zip_code = card_zip_code
		card.card_country = card_country

		card.facebook_link = facebook_link
		card.twitter_link = twitter_link
		card.instagram_link = instagram_link
		card.linkedin_link = linkedin_link

		card.save()

		
		return HttpResponseRedirect(reverse("order:dashboard", args=[card.id]))


	else:
		

		context = {"app_user": app_user, 'card':card, "order":order}
		return render(request, "order/dashboard.html", context )

order/templates/order/confirm_details.html
{% extends 'app_user/auth_base.html' %}
{% load static %}


{% block content %}

<body>
    {% include 'app_user/header.html' %}
    <section class="position-relative py-4 py-xl-5">
        <div class="container position-relative">
            <div class="row d-flex justify-content-center">
                <div class="col-md-8 col-lg-6 col-xl-5 col-xxl-4">
                    <h6 class="text-start mb-4 fw-700">Confirm Details</h6>
                    {% for rs in card_info %}
                    <div class="card mb-4 custom-radius">
                        <div class="card-body p-0 mx-3 my-3">
                            <div><a data-bs-toggle="collapse" aria-expanded="false" aria-controls="collapse-1" href="#collapse-1" role="button" id="toogleIcon1" class="fw-600 fs-14 primary-text text-decoration-none"><i id="icon1" class="fs-16 me-2 fa fa-caret-right"></i>Personal Information</a>
                                <div class="collapse" id="collapse-1">
                                    <form class="mt-3" method="post">
                                        <div class="row mb-3">
                                            <div class="col-md-6">
                                                <div><label class="form-label fw-600 fs-12" for="email"><strong>First Name</strong></label><input class="form-control" type="email" name="first-name" placeholder="{{ rs.card_first_name }} " required="" value="{{ rs.card_first_name }} " readonly=""></div>
                                            </div>
                                            <div class="col-md-6">
                                                <div><label class="form-label fw-600 fs-12" for="email"><strong>Last Name</strong></label><input class="form-control" type="email" name="last-name" placeholder="{{ rs.user.last_name }}" required="" value="{{ rs.card_last_name }}" readonly=""></div>
                                            </div>
                                        </div>
                                        <div class="mb-3"><label class="form-label fw-600 fs-12" for="email">Email</label><input class="form-control" type="email" name="email" placeholder="{{ rs.card_email }}" required="" value="{{ rs.card_email }}" readonly=""></div>
                                        <div class="mb-3"><label class="form-label fw-600 fs-12" for="email">Phone Number</label><input class="form-control" type="tel" placeholder="+234" required="" maxlength="14" minlength="11" value="{{ rs.card_phone_no }}" name="phone" readonly=""></div>
                                        <div class="mb-3"><label class="form-label fw-600 fs-12" for="file"><strong>Profile Image</strong></label>
                                        <div class="drag-image active" style="height: 250px;"><img alt="image" src="{{rs.card_profile_photo.url }}"><input class="form-control" type="file" id="profileImg" hidden="" required="" accept="image/*"></div>
                                        </div>
                                        <div class="mb-3"><label class="form-label fw-600 fs-12" for="website">Website</label><input class="form-control" type="url" placeholder="www.example.com" name="website" value="{{ rs.card_website }}" readonly=""></div>
                                        <div class="mb-3"><label class="form-label fw-600 fs-12" for="company-name"><strong>Company Name</strong></label><input class="form-control" type="url" placeholder="Enter Company Name" name="company-name" value="{{ rs.card_company }}" readonly=""></div>
                                        <div class="mb-3"><label class="form-label fw-600 fs-12" for="job-title"><strong>Job Title</strong><br></label><input class="form-control" type="url" placeholder="Enter Job Title" name="job-title" value="{{ rs.card_job_title}}" readonly=""></div>
                                        <div class="mb-3"><a class="btn btn-secondary d-block w-100" role="button">Edit</a></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-4 custom-radius">
                        <div class="card-body p-0 mx-3 my-3">
                            <div><a data-bs-toggle="collapse" aria-expanded="false" aria-controls="collapse-2" href="#collapse-2" role="button" id="toogleIcon2" class="fw-600 fs-14 primary-text text-decoration-none"><i id="icon2" class="fs-16 me-2 fa fa-caret-right"></i><strong>Address</strong></a>
                                <div class="collapse" id="collapse-2">
                                    <form class="mt-3" method="post">
                                        <div class="mb-3"><label class="form-label fw-600 fs-12" for="street"><strong>Street Address</strong><br></label><input class="form-control" type="url" placeholder="123 Silicon Street" name="street" required="" value="{{ rs.card_address }}" readonly=""></div>
                                        <div class="row mb-3">
                                            <div class="col-md-6">
                                                <div><label class="form-label fw-600 fs-12" for="email"><strong>City</strong><br></label><input class="form-control" type="email" name="city" placeholder="Ikeja" required="" value="{{ rs.card_city }}" readonly=""></div>
                                            </div>
                                            <div class="col-md-6">
                                                <div><label class="form-label fw-600 fs-12" for="email"><strong>State</strong><br></label><input class="form-control" type="email" name="state" placeholder="Lagos" required="" value="{{ rs.card_state }}" readonly=""></div>
                                            </div>
                                        </div>
                                        <div class="mb-3"><label class="form-label fw-600 fs-12" for="zip">Zip</label><input class="form-control" type="number" name="zip" placeholder="00000" value="{{ rs.card_zip_code }}" readonly=""></div>
                                        <div class="mb-3"><label class="form-label fw-600 fs-12" for="country"><strong>Country</strong><br></label><input class="form-control" type="text" name="country" value="{{ rs.card_country }}" placeholder="Nigeria" readonly=""></div>
                                        <div class="mb-3"><a class="btn btn-secondary d-block w-100" role="button">Edit</a></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="card mb-4 custom-radius">
                        <div class="card-body p-0 mx-3 my-3">
                            <div><a data-bs-toggle="collapse" aria-expanded="false" aria-controls="collapse-3" href="#collapse-3" role="button" id="toogleIcon3" class="fw-600 fs-14 primary-text text-decoration-none"><i id="icon3" class="fs-16 me-2 fa fa-caret-right"></i><strong>Social Media</strong></a>
                                <div class="collapse" id="collapse-3">
                                    <form class="mt-3" method="post">
                                        <div class="mb-3"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="1em" height="1em" fill="currentColor" class="fs-5 me-2" style="color: #1877F2;">
                                                <!--! Font Awesome Free 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2022 Fonticons, Inc. -->
                                                <path d="M504 256C504 119 393 8 256 8S8 119 8 256c0 123.78 90.69 226.38 209.25 245V327.69h-63V256h63v-54.64c0-62.15 37-96.48 93.67-96.48 27.14 0 55.52 4.84 55.52 4.84v61h-31.28c-30.8 0-40.41 19.12-40.41 38.73V256h68.78l-11 71.69h-57.78V501C413.31 482.38 504 379.78 504 256z"></path>
                                            </svg><label class="form-label fw-600 fs-12" for="facebook"><strong>Facebook</strong><br></label><input class="form-control" type="url" placeholder="eg. www.facebook.com/page" name="facebook" value="{{ rs.facebook_link }}" readonly=""></div>
                                        <div class="mb-3"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512" width="1em" height="1em" fill="currentColor" class="fs-5 me-2" style="color: #1D9BF0;">
                                                <!--! Font Awesome Free 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2022 Fonticons, Inc. -->
                                                <path d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"></path>
                                            </svg><label class="form-label fw-600 fs-12" for="twitter">Twitter</label><input class="form-control" type="url" placeholder="eg. www.twitter.com/page" name="twitter" value="{{ rs.twitter_link }}" readonly=""></div>
                                        <div class="mb-3"><i class="fab fa-instagram ig-logo me-2 fs-5 fw-700" aria-hidden="true"></i><label class="form-label fw-600 fs-12" for="instagram"><strong>Instagram</strong></label><input class="form-control" type="url" placeholder="eg. www.instagram.com/username" name="instagram" value="{{ rs.instagram_link }}" readonly=""></div>
                                        <div class="mb-3"><svg xmlns="http://www.w3.org/2000/svg" viewBox="-32 0 512 512" width="1em" height="1em" fill="currentColor" class="fs-5 me-2" style="color: #0a66c2;">
                                                <!--! Font Awesome Free 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License) Copyright 2022 Fonticons, Inc. -->
                                                <path d="M416 32H31.9C14.3 32 0 46.5 0 64.3v383.4C0 465.5 14.3 480 31.9 480H416c17.6 0 32-14.5 32-32.3V64.3c0-17.8-14.4-32.3-32-32.3zM135.4 416H69V202.2h66.5V416zm-33.2-243c-21.3 0-38.5-17.3-38.5-38.5S80.9 96 102.2 96c21.2 0 38.5 17.3 38.5 38.5 0 21.3-17.2 38.5-38.5 38.5zm282.1 243h-66.4V312c0-24.8-.5-56.7-34.5-56.7-34.6 0-39.9 27-39.9 54.9V416h-66.4V202.2h63.7v29.2h.9c8.9-16.8 30.6-34.5 62.9-34.5 67.2 0 79.7 44.3 79.7 101.9V416z"></path>
                                            </svg><label class="form-label fw-600 fs-12" for="linkedin"><strong>LinkedIn</strong></label><input class="form-control" type="url" placeholder="{{ rs.linkedin_link }}" name="linkedin" value="{{ rs.linkedin_link }}" readonly=""></div>
                                        <div class="mb-3"><a class="btn btn-secondary d-block w-100" role="button">Edit</a></div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div><a class="btn btn-dark d-block w-100" role="button" href="{% url 'order:complete' rs.id %}">Save</a></div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
{% endblock %}

order/templates/order/order_complete.html
{% extends 'app_user/auth_base.html' %}
{% load static %}


{% block content %}

<body>
    <div class="vh-100">
        {% include 'app_user/header.html' %}
        <div class="container h-75">
            <div class="row d-flex justify-content-center h-75">
                <div class="col-md-8 text-center d-flex justify-content-center align-items-center">
                    <div class="w-100"><svg width="80" height="80" viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg">
<rect width="120" height="120" rx="60" fill="#E0FFDE"/>
<path d="M60 112.5C46.0761 112.5 32.7226 106.969 22.8769 97.1231C13.0312 87.2775 7.5 73.9239 7.5 60C7.5 46.0761 13.0312 32.7226 22.8769 22.8769C32.7226 13.0312 46.0761 7.5 60 7.5C73.9239 7.5 87.2775 13.0312 97.1231 22.8769C106.969 32.7226 112.5 46.0761 112.5 60C112.5 73.9239 106.969 87.2775 97.1231 97.1231C87.2775 106.969 73.9239 112.5 60 112.5ZM60 120C75.913 120 91.1742 113.679 102.426 102.426C113.679 91.1742 120 75.913 120 60C120 44.087 113.679 28.8258 102.426 17.5736C91.1742 6.32141 75.913 0 60 0C44.087 0 28.8258 6.32141 17.5736 17.5736C6.32141 28.8258 0 44.087 0 60C0 75.913 6.32141 91.1742 17.5736 102.426C28.8258 113.679 44.087 120 60 120Z" fill="#E0FFDE"/>
<path d="M82.2746 37.2749C82.2212 37.3267 82.1711 37.3818 82.1246 37.4399L56.0771 70.6274L40.3796 54.9224C39.3133 53.9288 37.9029 53.3879 36.4457 53.4136C34.9884 53.4393 33.598 54.0296 32.5674 55.0602C31.5368 56.0908 30.9465 57.4812 30.9208 58.9385C30.8951 60.3957 31.436 61.8061 32.4296 62.8724L52.2746 82.7249C52.8092 83.2585 53.4458 83.679 54.1465 83.9613C54.8471 84.2436 55.5975 84.3818 56.3527 84.3678C57.1079 84.3538 57.8526 84.1879 58.5423 83.8798C59.232 83.5718 59.8526 83.128 60.3671 82.5749L90.3071 45.1499C91.3266 44.0799 91.884 42.6516 91.8588 41.1739C91.8336 39.6962 91.2279 38.2878 90.1725 37.2531C89.1172 36.2185 87.697 35.6407 86.2191 35.6448C84.7412 35.6489 83.3242 36.2344 82.2746 37.2749Z" fill="#4AE551"/>
</svg>

                        <p class="fw-700 fs-20 mt-3">Card details updated successfully </p><a class="btn btn-dark w-50 mt-4 fs-16" role="button" href="{% url 'order:dashboard' card.id %}">Return Home </a>

                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}