app_user/urls.py
from django.urls import path
from . import views

app_name = "app_user"

urlpatterns = [

	path("sign-in/", views.SignInView, name="sign_in"),
	path("sign-up/", views.SignUpView, name="sign_up"),
	path("sign-up/complete/", views.CompleteSignUpView, name="complete_sign_up"),
	path("sign-out/", views.SignOutView, name="sign_out"),
	path("verified/", views.VerifiedView, name="verified"),
    path("app/", views.DashboardView, name="dashboard"),

]

card/urls.py
from django.urls import path
from . import views

app_name = "card"

urlpatterns = [

    path("<str:app_user>/", views.MyCardView, name="card"),
    
    path("card/", views.CardView, name="card"),

]

payment/urls.py
from django.urls import path
from . import views

app_name = "payment"

urlpatterns = [

    path("make-payment/<int:order_id>/pay-now/", views.PayNow, name="make_payment"),
	path("confirm-payment/<int:order_id>/", views.ConfirmPayment, name="confirm_payment"),
	path("success/", views.Success, name="success"),

]

thispass/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path 


urlpatterns = [
    path("", include("main.urls")),
    path('admin/', admin.site.urls),
    path("app/", include("app_user.urls")),
    path("card", include("card.urls")),
    path("order/", include("order.urls")),
    path("payment/", include("payment.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

payment/models.py
from django.db import models
from django.utils import timezone

from app_user.models import *
from card.models import *
from order.models import *


# Create your models here.

class Payment(models.Model):
	order = models.ForeignKey(Order, on_delete=models.CASCADE)
	status = models.BooleanField(default=False)

	pub_date = models.DateTimeField(default=timezone.now)

	def __str__(self):
		return self.order.code

payment/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth import login, logout, authenticate

from django.utils.crypto import get_random_string

from datetime import datetime
import datetime as dt
import requests

from card.models import *
from payment.models import *
from order.models import *

#from resume.models import Resume



def PayNow(request, order_id):
    order = Order.objects.get(id=order_id)
    app_user = AppUser.objects.get(user__pk=request.user.id)
    if request.method == "POST":
        return HttpResponseRedirect(reverse("payment:confirm_payment", args=[order.id,]))



    else:

        context = {"order": order, "app_user":app_user}
        return render(request, "payment/make_payment.html", context )


def ConfirmPayment(request, order_id):
    app_user = AppUser.objects.get(user__pk=request.user.id)
    order = Order.objects.get(id=order_id)
    if request.method == "POST":
        

        payment = Payment.objects.create(order=order)
        payment.status = True
        payment.save()

        return HttpResponseRedirect(reverse("order:update_appuser", args=[order.id,]))

    else:
        context = {"order": order, "app_user":app_user}
        return render(request, "payment/confirm_payment.html", context )


def Success(request):
    if request.method == "POST":
        pass
    

    else:
        context = {}
        return render(request, "payment/success.html", context )

payment/templates/payment/confirm_payment.html
{% extends 'app_user/auth_base.html' %}
{% load static %}


{% block content %}

<body>
    <div class="vh-100">
        {% include 'app_user/header.html' %}
        <div class="container h-75">
            <div class="row d-lg-flex justify-content-lg-center h-75">
                <div class="col-md-8 text-center d-lg-flex justify-content-lg-center align-items-lg-center">
                    <div class="w-100"><svg width="80" height="80" viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg">
<rect width="120" height="120" rx="60" fill="#E0FFDE"/>
<path d="M60 112.5C46.0761 112.5 32.7226 106.969 22.8769 97.1231C13.0312 87.2775 7.5 73.9239 7.5 60C7.5 46.0761 13.0312 32.7226 22.8769 22.8769C32.7226 13.0312 46.0761 7.5 60 7.5C73.9239 7.5 87.2775 13.0312 97.1231 22.8769C106.969 32.7226 112.5 46.0761 112.5 60C112.5 73.9239 106.969 87.2775 97.1231 97.1231C87.2775 106.969 73.9239 112.5 60 112.5ZM60 120C75.913 120 91.1742 113.679 102.426 102.426C113.679 91.1742 120 75.913 120 60C120 44.087 113.679 28.8258 102.426 17.5736C91.1742 6.32141 75.913 0 60 0C44.087 0 28.8258 6.32141 17.5736 17.5736C6.32141 28.8258 0 44.087 0 60C0 75.913 6.32141 91.1742 17.5736 102.426C28.8258 113.679 44.087 120 60 120Z" fill="#E0FFDE"/>
<path d="M82.2746 37.2749C82.2212 37.3267 82.1711 37.3818 82.1246 37.4399L56.0771 70.6274L40.3796 54.9224C39.3133 53.9288 37.9029 53.3879 36.4457 53.4136C34.9884 53.4393 33.598 54.0296 32.5674 55.0602C31.5368 56.0908 30.9465 57.4812 30.9208 58.9385C30.8951 60.3957 31.436 61.8061 32.4296 62.8724L52.2746 82.7249C52.8092 83.2585 53.4458 83.679 54.1465 83.9613C54.8471 84.2436 55.5975 84.3818 56.3527 84.3678C57.1079 84.3538 57.8526 84.1879 58.5423 83.8798C59.232 83.5718 59.8526 83.128 60.3671 82.5749L90.3071 45.1499C91.3266 44.0799 91.884 42.6516 91.8588 41.1739C91.8336 39.6962 91.2279 38.2878 90.1725 37.2531C89.1172 36.2185 87.697 35.6407 86.2191 35.6448C84.7412 35.6489 83.3242 36.2344 82.2746 37.2749Z" fill="#4AE551"/>
</svg>

                        <p class="fw-700 fs-20 mt-3">Order Successful <br> Order Code: <b style="color:green">{{ order.code }}<b></p>
                            <form method="post">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-dark w-50 mt-4" type="button">Proceed to set up your card</button> 
                              </form>   
                        
                    </div>
                </div>
            </div>
        </div>
    </div>


<body class="vh-100">
    {% include 'app_user/header.html' %}
    <div class="container d-flex align-items-xl-center h-100">
        <div class="my-12">
            <h1 class="text-center fw-700 fs-40">Almost there,</h1>
            <div class="row mt-5s">
                <div class="col-lg-12 px-5 mb-5">
                    <div class="card py-5 px-3 custom-radius">
                        <div class="card-body">
                            <p class="card-text mb-5">Confirm your payment</p>
                            <form method="post">
                                {% csrf_token %}
                                <button type="submit" btn btn-dark type="button"> Confirm! </button> 
                              </form>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>



{% endblock %}

payment/templates/payment/make_payment.html
{% extends 'app_user/auth_base.html' %}
{% load static %}

{% block content %}

<body>
    <div class="vh-100">
        {% include 'app_user/header.html' %}
        <div class="container h-75">
            <div class="row d-flex justify-content-center h-75">
                <div class="col-md-8 text-center d-flex justify-content-center align-items-center">
                    <div class="w-100"><svg width="80" height="80" viewBox="0 0 120 120" fill="none" xmlns="http://www.w3.org/2000/svg">
<rect width="120" height="120" rx="60" fill="#E0FFDE"/>
<path d="M60 112.5C46.0761 112.5 32.7226 106.969 22.8769 97.1231C13.0312 87.2775 7.5 73.9239 7.5 60C7.5 46.0761 13.0312 32.7226 22.8769 22.8769C32.7226 13.0312 46.0761 7.5 60 7.5C73.9239 7.5 87.2775 13.0312 97.1231 22.8769C106.969 32.7226 112.5 46.0761 112.5 60C112.5 73.9239 106.969 87.2775 97.1231 97.1231C87.2775 106.969 73.9239 112.5 60 112.5ZM60 120C75.913 120 91.1742 113.679 102.426 102.426C113.679 91.1742 120 75.913 120 60C120 44.087 113.679 28.8258 102.426 17.5736C91.1742 6.32141 75.913 0 60 0C44.087 0 28.8258 6.32141 17.5736 17.5736C6.32141 28.8258 0 44.087 0 60C0 75.913 6.32141 91.1742 17.5736 102.426C28.8258 113.679 44.087 120 60 120Z" fill="#E0FFDE"/>
<path d="M82.2746 37.2749C82.2212 37.3267 82.1711 37.3818 82.1246 37.4399L56.0771 70.6274L40.3796 54.9224C39.3133 53.9288 37.9029 53.3879 36.4457 53.4136C34.9884 53.4393 33.598 54.0296 32.5674 55.0602C31.5368 56.0908 30.9465 57.4812 30.9208 58.9385C30.8951 60.3957 31.436 61.8061 32.4296 62.8724L52.2746 82.7249C52.8092 83.2585 53.4458 83.679 54.1465 83.9613C54.8471 84.2436 55.5975 84.3818 56.3527 84.3678C57.1079 84.3538 57.8526 84.1879 58.5423 83.8798C59.232 83.5718 59.8526 83.128 60.3671 82.5749L90.3071 45.1499C91.3266 44.0799 91.884 42.6516 91.8588 41.1739C91.8336 39.6962 91.2279 38.2878 90.1725 37.2531C89.1172 36.2185 87.697 35.6407 86.2191 35.6448C84.7412 35.6489 83.3242 36.2344 82.2746 37.2749Z" fill="#4AE551"/>
</svg>

                        <p class="fw-700 fs-20 mt-3">Make you Payment </p>
                        <form>
                        <script src="https://js.paystack.co/v1/inline.js"></script>
                            <button class="btn btn-dark w-50 mt-4 fs-16" type="button" onclick="payWithPaystack()"> Pay with paystack </button> 
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>




<!-- place below the html form -->
<script>
    function payWithPaystack(){
      var handler = PaystackPop.setup({
        key: 'pk_test_33ebd1961880161ee028ef962b6c34eae07b5718',
        email: '{{ order.app_user.user.email }}',
        amount: {% widthratio order.total 1 100 %},
        ref: ''+Math.floor((Math.random() * 1000000000) + 1), // generates a pseudo-unique reference. Please replace with a reference you generated. Or remove the line entirely so our API will generate one for you
        metadata: {
           custom_fields: [
              {
                  display_name: '{{ order.app_user.user.email }}',
                  variable_name: '{{ order.app_user.user.email }}',
                  value: '{{ order.app_user.phone_no }}'
              }
           ]
        },
        callback: function(response){
            alert('success. transaction ref is ' + response.reference);
            window.location.href = "{% url 'payment:confirm_payment' order.id %}";
        },
        onClose: function(){
            alert('window closed');
        }
      });
      handler.openIframe();
    }
  </script>
  
{% endblock %}

payment/templates/payment/success.html
{% extends 'app_user/auth_base.html' %}
{% load static %}

{% block content %}

<body class="vh-100">
    {% include 'app_user/header.html' %}
    <div class="container d-flex align-items-xl-center h-100">
        <div class="my-12">
            <h1 class="text-center fw-700 fs-40">You're done,</h1>
            <div class="row mt-5s">
                <div class="col-lg-12 px-5 mb-5">
                    <div class="card py-5 px-3 custom-radius">
                        <div class="card-body">
                            <p class="card-text mb-5">Congratulations</p>
                            <a href="{% url 'app_user:dashboard' %}">Back Home</a>
                        </div>
                    </div>
                </div>
                
            </div>
        </div>
    </div>

{% endblock %}